food/urls.py
from django.urls import path
from . import views

app_name = 'food'
urlpatterns = [
    #/food/
    #path('', views.index, name='index'),
    path('', views.IndexClassView.as_view(), name='index'),
    #/food/1
    #path('<int:item_id>/',views.detail,name='detail'),
    path('<int:pk>/',views.FoodDetail.as_view(),name='detail'),
    path('item/',views.items, name='item'),
    #add_items
    #path('add/',views.create_item, name='create_item'),
    path('add/',views.CreateItem.as_view(), name='create_item'),
    #update_item
    path('update/<int:id>',views.update_item, name='update_item'),
    #delete_item
    path('delete/<int:id>',views.delete_item, name='delete_item'),

    ]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('register/', user_views.register,name='register'),
    path('login/', authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/', authentication_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',user_views.profilepage,name='profile'),
]



urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class item(models.Model):
    def __str__(self):
        return self.item_name

    user_name=models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    item_name=models.CharField(max_length=200)
    item_desc=models.CharField(max_length=200)
    item_price=models.IntegerField()
    item_image = models.CharField(max_length=500, default="https://livingstonbagel.com/wp-content/uploads/2016/11/food-placeholder.jpg")
    def get_absolute_url(self):
        return reverse("food:detail", kwargs={"pk": self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpg',upload_to='profile_pictures')
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

food/forms.py
from django import forms
from .models import item

class ItemForm(forms.ModelForm):
    class Meta:
        model = item
        fields = ['item_name','item_desc','item_price','item_image']

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username','email','password1','password2']

food/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import item
from django.template import loader
from .forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView

# Create your views here.
#### This is function based views
# def index(request):
#     item_list=item.objects.all()
#     #template=loader.get_template('food/index.html')
#     context={
#         'item_list':item_list,
#     }
#     return render(request,'food/index.html',context)

class IndexClassView(ListView):
    model = item;
    template_name = 'food/index.html'
    context_object_name = 'item_list'


def items(request):
    return HttpResponse('this view is for item')

###This is function based view
# def detail(request,item_id):
#     Item=item.objects.get(pk=item_id)
#     context={
#         'item': Item,
#     return render(request,'food/detail.html',context)

class FoodDetail(DetailView):
    model = item
    template_name = 'food/detail.html'
#this is function based views
# def create_item(request):
#     form = ItemForm(request.POST or None)
#
#     if form.is_valid():
#         form.save()
#         return redirect('food:index')
#
#     return render(request,'food/item-form.html',{'form': form})

#This is class based views for create item
class CreateItem(CreateView):
    model=item;
    fields=['item_name','item_desc','item_price','item_image']
    template_name='food/item-form.html'

    def form_valid(self,form):
        form.instance.user_name = self.request.user

        return super().form_valid(form)


def update_item(request, id):
    items=item.objects.get(id=id)
    form=ItemForm(request.POST or None, instance=items)

    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request,'food/item-form.html',{'form':form,'items':items})
def delete_item(request, id):
    items=item.objects.get(id=id)

    if request.method == 'POST':
        items.delete()
        return redirect('food:index')

    return render(request,'food/item-delete.html',{'items':items})

users/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import RegisterForm

# Create your views here.

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f'Welcome {username}, your account is created')
            return redirect('login')
    else:
        form = RegisterForm()
    return render (request,'users/register.html',{'form':form})

@login_required
def profilepage(request):
    return render(request,'users/profile.html')

food/templates/food/base.html
{%load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" herf="{% static "food/style.css" %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title>FoodApp</title>
</head>
<body>
    <nav class=" navbar navbar-dark bg-dark">
        <a href="{% url 'food:index' %}" class="navbar-brand">FoodApp</a>
        <div class="navbar">
            {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'food:create_item' %}">Add Item</a>
            {% else %}
                <a href="{% url 'login' %}">Add Item</a>
            {% endif %}
            {% if user.is_authenticated %}
                <a href="{% url 'profile' %}">Profile</a>&nbsp&nbsp&nbsp&nbsp
                <a href="{% url 'logout' %}">Logout</a>
            {% else %}
                <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                <a href="{% url 'login' %}">Login</a>
            {% endif %}
        </div>
    </nav>
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
        {% endfor %}
    {% endif %}
    {% block body %}
    {% endblock %}

</body>
</html>

food/templates/food/detail.html
{% extends 'food/base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img height="300px" src="{{ item.item_image }}" class="card"/>
        </div>

        <div class="col-md-6">
            <h1>{{object.item_name}}</h1>
            <h2>{{object.item_desc}}</h2>
            <h3>Rs. {{object.item_price}}</h3>
            <a class="btn btn-danger" href="{% url 'food:delete_item' item.id %}">Delete</a>
            <a class="btn btn-warning" href="{% url 'food:update_item' item.id %}">Update</a>
        </div>
    </div>
</div>

{% endblock %}

food/templates/food/index.html
{% extends 'food/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    </head>
<body>

    {% block body %}
    {% for item in item_list %}
        <div class="row">
            <div class="col-md-3 offset-md-2">
                <img class="card" height="150px" src="{{ item.item_image}}"/>
            </div>
            <div class="col-md-4">
                <h3>{{ item.item_name }}</h3>
                <h5>{{ item.item_desc}}</h5>
                <h6>Rs.{{ item.item_price}}</h6>
                <h6 style="color:Tomato;">Added By: {{ item.user_name }}</h6>
            </div>
            <div class="col-md-2">
                <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>

            </div>
        </div>

    {% endfor %}
    {% endblock %}
    <ul>
        <li>

            <a href="">{{item.id}} ---{{item.item_name}}</a>
        </li>
    </ul>

</body>
</html>

food/templates/food/item-delete.html
{% extends 'food/base.html' %}
{% block body %}
<center>
<form method="POST">
    {% csrf_token %}
    <h2>Are you sure you want to delete {{ items.item_name }}</h2>
    <button type="submit" class="btn btn-danger">Confirm</button>
    <a class="btn btn-primary" href="{% url 'food:index' %}" role="button">Not now</a>
</form>
</center>

{% endblock %}

food/templates/food/item-form.html
{% extends 'food/base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Add item
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {{ form }}
                        <button class="btn-info" type="submit">Add</button>
                        </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'food/base.html' %}
{% block body%}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Login
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                {{ field.name}}
                                {{ field }}
                            </div>
                        {% endfor %}
                        <button class="btn-info" type="submit">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{%endblock%}

users/templates/users/logout.html
{%load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" herf="{% static "food/style.css" %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title>Title</title>
</head>
<body>
    <nav class=" navbar navbar-dark bg-dark">
        <a href="{% url 'food:index' %}" class="navbar-brand">FoodApp</a>
        <div class="navbar">
            <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
            <a href="{% url 'login' %}">Login</a>
        </div>
    </nav>
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
        {% endfor %}
    {% endif %}
    {% block body %}
    <center>
    <h1>You have been successfully logged out !!!</h1><br>
    <h2>Please login and enjoy our services !!!<br>
    Thankyou !!!
    </h2>
    </center>
    {% endblock %}

</body>
</html>

users/templates/users/profile.html
{% extends 'food/base.html' %}
{% block body %}


<center>
<h1>Username : {{ user.username }}</h1>
<h1>Profile photo : <img width="100px" height="100px" src="{{ user.profile.image.url }}"></h1>

</center>





{% endblock %}

users/templates/users/register.html
{% extends 'food/base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Register
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                      {% csrf_token %}
                      {% for field in form %}
                          <div class="form-group">
                            {{ field.name }}
                            <br>
                            {{ field }}
                          </div>
                      {% endfor %}
                      <button class="btn-info" type="submit">Register</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock%}